language: node_js

node_js:
  - "5"
  - "6"
  - "7"

env:
  global:
    - USE_ORACLE_DUMMY=1

before_script:
  - npm install -g gulp

script:
  - "gulp lint"
  - "gulp test"
  - "gulp coverage"

install:
  - npm install

notifications:
  email:
    - dieter.oberkofler@gmail.com
